language: scala
scala:
  - 2.11.7
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
  - psql -c 'create role amutake createdb login;' -U postgres
  - psql -c 'create database andon_test;' -U amutake
  - sbt "flywayMigrate"
